config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr|es/ do
    root to: 'home#index'

    get 'about-us', to: 'home#show', as: 'about_us'

    # Account related routes
    get 'account/bookmarked', to: 'account/posts#bookmarked', as: 'bookmarked'
    get 'account/profile', to: 'account#index', as: 'profile'
    get  'account', to: 'account#edit'
    post 'account', to: 'account#update'

    namespace :account do
      resources :posts, only: [:index]
    end

    
    # Post related routes
    resources :posts do
      resources :comments, only: [:create, :destroy]
    end
    # Add comments here later
    get 'search', to: 'posts#index', as: 'search'
    get 'authors/:username', to: 'users#show', as: :username
    get 'authors/:username/posts', to: 'posts#index', as: :username_posts
    get 'all-posts', to: 'posts#all_posts', as: 'all_posts'

    # Tags related routes
    resources :tags, only: [:create, :destroy]
    get 'tags/:name', to: 'posts#index', as: :name

    # User and session related routes
    resources :sessions, only: [:new, :create, :destroy]
    resources :users do
      resources :bookmarks, only: [:create, :destroy]
    end


    # Login and Sign up routes
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    # Routes for external authentication
    get '/auth/:provider/callback', to: 'sessions#omniauth'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Callbacks
  before_validation :downcase_email
  before_validation :downcase_username
  after_initialize :default_role!
  after_initialize :default_bio!

  # Validation rules
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: { case_sensitive: false }
  validates :username, length: { maximum: 15 }
  validates :password, confirmation: true
  validates :role, inclusion: { in: %w(registered author admin) }
  has_secure_password

  # Relationships
  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  has_many :comments, dependent: :destroy

  # Pagination
  paginates_per 6

  # Uploader
  # mount_uploader :avatar, AvatarUploader
  has_one_attached :avatar

  def self.from_omniauth(auth)
    # Creates a new user only if it doesn't exist
    where(email: auth.info.email).first_or_initialize do |user|
      user.name = auth.info.name
      user.username = auth.info.name.tr(" ", "_").truncate(14)
      user.email = auth.info.email
      if auth.info.uid
        user.uid = auth.info.uid
      end
      user.password = user.password_confirmation = SecureRandom.hex
    end
  end

  # Methods
  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_username
    self.username = username.downcase
  end

  def default_role!
    self.role ||= 'registered'
  end
  def default_bio!
    self.bio ||= 'No bio'
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Includes
  include RolesHelper

  # Before actions
  before_action :ensure_authenticated,   only: [:index, :edit, :update, :destroy] 
  before_action :set_user,               only: [:edit, :update, :destroy]
  before_action :authorize_to_edit_user, only: [:edit, :update]
  before_action :ensure_admin,           only: [:index, :destroy]

  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    if params[:username]
      @user = User.find_by(username: params[:username])
    else
      @user = User.find_by(id: params[:id])
    end

    return redirect_to root_path unless @user.role == 'author' || admin?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def edit
  end

  def update
    if @user.update(edit_user_params)
      redirect_to profile_path unless admin?
      redirect to users_path if admin?
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_to_edit_user
    redirect_to profile_path unless can_edit_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role, :username, :bio, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.js.erb
Users.removeUser('<%= @user.id %>');

app/views/users/edit.html.erb
<div class="content-wrapper">
  <!-- START Form -->
  <div class="form-container">
    <h1 class="alpha"><%= t('edit.modify') %></h1>
    <div class="alert alert--wide">
      <% @user.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
    <%= form_for @user, html: { class: 'form'} do |f| %>
      <!-- Name -->
      <div class="input">
        <div>
          <%= f.label :name, class: 'input__label' %>
        </div>
        <div>
          <%= f.text_field :name, class: 'input__field' %>
        </div>
      </div>
      <!-- Username -->
      <div class="input">
        <div>
          <%= f.label :username, class: 'input__label' %>
        </div>
        <div>
          <%= f.text_field :username, class: 'input__field' %>
        </div>
      </div>
      <!-- Email -->
      <div class="input">
        <div>
          <%= f.label :email, class: 'input__label' %>
        </div>
        <div>
          <%= f.email_field :email, class: 'input__field' %>
        </div>
      </div>
      <!-- Avatar -->
      <div class="input">
        <div>
          <%= f.label :avatar, "Avatar", class: 'input__label' %>
        </div>
        <div>
          <%= f.file_field :avatar, class: 'input__field' %>
        </div>
      </div>
      <!-- Role -->
      <% if admin? %>
        <div class="input">
          <div>
            <%= f.label :role, class: 'input__label' %>
          </div>
          <div>
            <%= f.select :role,  [["Admin", "admin"], ["Author", "author"], ["Registered", "registered"]], class: 'input__field' %>
          </div>
        </div>
      <% end %>
      <!-- Bio -->
      <% if @user.role == 'author'%>
        <div class="input">
          <div>
            <%= f.label :bio, class: 'input__label' %>
          </div>
          <div class="input--textarea input--post-text">
            <%= f.text_area :bio, class: 'input__field'%>
          </div>
        </div>
      <% end %>
      <!-- Cancel link -->
      <div class="form__text">
        <%= link_to t('edit.cancel'), profile_path %>
      </div>
      <!-- Submit -->
      <div class="form__text input__btn--alone">
        <div class="prompt">
          <%= f.submit t('edit.modify'), class: 'btn btn--cta prompt__confirm' %>
        </div>
      </div>
    <% end %>
    
  </div>

  <!-- END Form -->
</div>

app/views/users/index.html.erb
<div class="content-wrapper">
  <h1>Usuarios</h1>
  <p><%= page_entries_info @users %></p>
  <ul class="bare-list cards">
    <% @users.each do |user| %>
      <li class="user-card" id="user-<%= user.id %>">
        <div class="user-card__thumb">
          <%= image_tag(default_avatar(user), alt: 'Avatar', class: 'avatar') %>
        </div>
        <div class="user-card__main">
          <h3 class="user-card__username">
          <%= link_to user_path(user) do %>
            <% if user.name.present? %>
              <%= user.name %>
            <% else %>
              <%= user.username %>
            <% end %>
          <% end %>
          </h3>
          <div class="user-card__meta">
            <h4 class="user-card__account"><%= t('user.registered') %> <time datetime="<%= user.created_at %>"><%= l(user.created_at, format: :concise) %></time></h4>
            <h4 class="user-card__account"><%= t('user.role') %>: <%= user.role %></h4>
            <% if user.role == 'author' %>
              <h4 class="user-card__account"><%= t('header.posts') %> <%= user.posts.count %></h4>
            <% end %>
              <h4 class="user-card__account"><%= t('post.comments') %>: <%= user.comments.count %></h4>
          </div>
        </div>
        <div class="user-card__form">
          <%= link_to edit_user_path(user), class: 'btn btn--icon', role: 'button' do %>
            <i class="fal fa-user-edit"></i> 
            <%= t('edit.modify') %>
          <% end %>

          <%= link_to user_path(user), class: 'btn btn--icon btn--warning', role: 'button', method: :delete, remote: true do %>
            <i class="fal fa-trash"></i>
            <%= t('edit.delete') %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="pagination-container">
    <%= paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="content-wrapper">
  <!-- START Form -->
  <div class="form-container">
    <h1 class="alpha"><%= t('header.signup') %></h1>
    <div class="form__text">
      <span><%= t('register.message') %> <%= link_to t('register.messageLink'), login_path %></span>
    </div>
    <%= link_to '/auth/google_oauth2', class: 'btn btn--google' do %>
      <%= image_tag('google.png', alt: 'Google Logo') %> <span><%= t('register.google') %></span>
    <% end %>
    <%= form_for @user, html: { class: 'form'} do |f| %>
      <div class="alert alert--wide">
        <% @user.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
      <!-- Name -->
      <div class="input">
        <div>
          <%= f.label :name, class: 'input__label' %>
        </div>
        <div>
          <%= f.text_field :name, class: 'input__field' %>
        </div>
      </div>
      <!-- Username -->
      <div class="input">
        <div>
          <%= f.label :username, class: 'input__label' %>
        </div>
        <div>
          <%= f.text_field :username, class: 'input__field', required: 'required' %>
        </div>
      </div>
      <!-- Email -->
      <div class="input">
        <div>
          <%= f.label :email, class: 'input__label' %>
        </div>
        <div>
          <%= f.email_field :email, class: 'input__field', required: 'required' %>
        </div>
      </div>
      <!-- Password -->
      <div class="input">
        <div>
          <%= f.label :password, class: 'input__label' %>
        </div>
        <div>
          <%= f.password_field :password, class: 'input__field', required: 'required' %>
        </div>
      </div>
      <!-- Password confirmation -->
      <div class="input">
        <div>
          <%= f.label :password_confirmation, class: 'input__label' %>
        </div>
        <div>
          <%= f.password_field :password_confirmation, class: 'input__field', required: 'required' %>
        </div>
      </div>
      <!-- Submit -->
      <div class="form__text input__btn--alone">
        <div class="prompt">
          <%= f.submit t('header.signup'), class: 'btn btn--cta prompt__confirm' %>
        </div>
      </div>
    <% end %>
    
  </div>

  <!-- END Form -->
</div>

app/views/users/show.html.erb
<% if logged_in? && admin? %>
  <div class="modify-bar">
    <div class="content-wrapper">
      <ul class="bare-list">
        <li>
          <%= link_to edit_user_path(@user), class: 'btn btn--icon', role: 'button' do %>
            <i class="fal fa-user-edit"></i> 
            <%= t('edit.modify') %>
          <% end %>
        </li>
        <li>
          <%= link_to user_path(@user), class: 'btn btn--icon btn--warning', role: 'button', method: :delete do %>
            <i class="fal fa-trash"></i>
            <%= t('edit.delete') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>
<div class="content-wrapper">
  <div class="user">
    <div class="user__header">
    <% if @user.name.present? %>
      <h1 class="alpha"><%= @user.name %></h1>
    <% else %>
      <h1 class="alpha"><%= @user.username %></h1>
    <% end %>
    <% if logged_in? && admin? %>
      <span><%= t('user.registered') %> <time datetime="<%= @user.created_at %>"><%= l(@user.created_at, format: :concise) %></time></span>
      <span><%= t('user.role') %>: <%= @user.role %></button>
    <% end %>
    </div>
    <div class="user__thumb">
      <%= image_tag(default_avatar(@user), alt: 'Avatar', class: 'avatar') %>
    </div>
    <div class="user__main">
      <h3 class="user__title">
        <%= t('user.bio') %>:
      </h3>
      <div class="user__bio"><%= markdown(@user.bio) %></div>
    </div>
    <div class="user__footer">
      <% if @user.posts.any? %>
        <%= link_to t('header.posts'), username_posts_path(@user.username), class: 'btn' %>
      <% end %>
      
    </div>
  </div>
</div>