config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr|es/ do
    root to: 'home#index'

    get 'about-us', to: 'home#show', as: 'about_us'

    # Account related routes
    get 'account/bookmarked', to: 'account/posts#bookmarked', as: 'bookmarked'
    get 'account/profile', to: 'account#index', as: 'profile'
    get  'account', to: 'account#edit'
    post 'account', to: 'account#update'

    namespace :account do
      resources :posts, only: [:index]
    end

    
    # Post related routes
    resources :posts do
      resources :comments, only: [:create, :destroy]
    end
    # Add comments here later
    get 'search', to: 'posts#index', as: 'search'
    get 'authors/:username', to: 'users#show', as: :username
    get 'authors/:username/posts', to: 'posts#index', as: :username_posts
    get 'all-posts', to: 'posts#all_posts', as: 'all_posts'

    # Tags related routes
    resources :tags, only: [:create, :destroy]
    get 'tags/:name', to: 'posts#index', as: :name

    # User and session related routes
    resources :sessions, only: [:new, :create, :destroy]
    resources :users do
      resources :bookmarks, only: [:create, :destroy]
    end


    # Login and Sign up routes
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    # Routes for external authentication
    get '/auth/:provider/callback', to: 'sessions#omniauth'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # Callbacks

  # Validation rules
  validates :tags, length: { maximum: 3, message: ": 3 are the maximum allowed." }
  validates :title, :body, presence: true

  # Relationships
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :comments, dependent: :destroy

  # Pagination
  paginates_per 6

  # Scopes
  scope :most_recent, -> { order(created_at: :desc).limit(6) }
  scope :title_contains, ->(term) { where('lower(title) LIKE ?', "%#{term}%") }
  scope :body_contains, ->(term) { where('lower(body) LIKE ?', "%#{term}%") }
  scope :tags_contain, ->(term) { joins(:tags).where('tags.name LIKE ?', "%#{term}%") }
  scope :search, ->(search_term) { title_contains(search_term) | tags_contain(search_term) | body_contains(search_term) }
  scope :tagged_with, ->(name) { Tag.find_by!(name: name).posts }

  # Methods

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :ensure_authenticated
  before_action :has_posts, only: [:index]

  def index
    @posts = current_user.posts.order(updated_at: :desc).page(params[:page])
  end

  def bookmarked
    @posts = current_user.bookmarked_posts.order(updated_at: :desc).page(params[:page])
  end

  private

  def has_posts
    redirect_to account_path unless admin? || author?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  # Includes
  include RolesHelper

  # Before Actions
  before_action :ensure_authenticated,   only: [:new, :create, :edit, :update, :destroy] 
  before_action :set_post,               only: %i[show edit update destroy]
  before_action :authorize_to_create_post, only: %i[new create]
  before_action :authorize_to_edit_post, only: %i[edit update destroy]
  before_action :ensure_admin,           only: %i[all_posts]

  def index
    if params[:name]
      @posts = Post.tagged_with(params[:name]).order(created_at: :desc)
    elsif params[:q]
      @search_term = params[:q]
      results = Post.search(@search_term.downcase)
      @posts = results.sort_by(&:created_at).reverse
    elsif params[:username]
      author = User.find_by(username: params[:username])
      @posts = author.posts.order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
    @tags = Tag.all.order(:name)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    user = current_user
    @post = Post.new(post_params)
    @post.user = user
    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit 
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.js
    end
  end

  def all_posts
    @posts = Post.all.order(updated_at: :desc).page(params[:page])
    @tags = Tag.all.order(:name)
    @tag = Tag.new
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_to_edit_post
    redirect_to root_path unless can_edit_post?(@post)
  end

  def authorize_to_create_post
    redirect_to root_path unless author? || admin?
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :preview_text, :image_url, :spotify_code, :tag_list, :tag, { tag_ids: []}, :tag_ids)
  end
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments_section.html.erb
  <!-- START Comments section-->
  <div class="post__comments post__section">
    <h3><%= t('post.comments') %></h3>
    <!-- START Comments form -->
    <% if logged_in? %>
      <div class="discussion comments--add">
        <%= form_for([post, comment], html: { class: 'input' }, remote: true ) do |f| %>
          <%= f.label :body, class: 'input__label sr-only' %>
          <%= f.text_field :body, class: 'input__field' %>
          <%= f.submit t('post.commentNew'), class: 'btn btn--cta'%>
        <% end %>
      </div>
    <% end %>
    <!-- END Comments form -->
    <!-- START Discussion -->
    <div class="discussion" id="discussion">
      <% comments.each do |comment| %>
        <div class="comment" id="comment-<%= comment.id %>">
          <div class="comment__avatar">
            <% if logged_in? && comment.user == current_user %>
              <%= link_to profile_path do %>
                <%= image_tag(default_avatar(comment.user), alt: 'Avatar', class: 'avatar') %>
              <% end %>
            <% elsif comment.user.role == 'author' %>
              <%= link_to username_path(comment.user.username) do %>
                <%= image_tag(default_avatar(comment.user), alt: 'Avatar', class: 'avatar') %>
              <% end %>
            <% else %>
              <%= image_tag(default_avatar(comment.user), alt: 'Avatar', class: 'avatar') %>
            <% end %>
          </div>
          <div class="comment__text">
            <p class="comment__user">
              <% if logged_in? && comment.user == current_user %>
                <%= link_to  comment.user.name, profile_path %>
              <% elsif comment.user.role == 'author' %>
                <%= link_to comment.user.name, username_path(comment.user.username) %>
              <% else %>
                <%= comment.user.name %>
              <% end %>
              <time  class="comment__time" datetime="<%= comment.created_at %>"> <%= time_ago_in_words(comment.created_at) %></time>
            </p>
            <p>
              <%= comment.body %>
            </p>
          </div>
          <% if logged_in? && can_delete_comment?(comment) %>
            <div class="comment__delete">
              <%= link_to post_comment_path(post, comment), class: 'btn btn--icon btn--warning', role: 'button', method: :delete, remote: true do %>
                <i class="fal fa-trash"></i>
                <%= t('edit.delete') %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <!-- END Discussion -->
    <!-- END Comments section-->
  </div>

app/views/posts/_filter.html.erb
<div class="filter">
  <input type="checkbox" class="toggler">
  <div class="filter__header">
    <p class="filter__text"><%= t('filter') %></p>
    <div class="arrow">
    </div>
  </div>
  <div class="filter__tags tags" id="tagsList">
    <ul class="tags__list">
      <% tags.each do |tag| %>
        <li class="btn btn--tag"><%= tag.name %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for post, html: { class: 'form'} do |f| %>
  <div class="alert alert--wide">
    <% post.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <!-- Title -->
  <div class="input">
    <div>
      <%= f.label :title, class: 'input__label' %>
    </div>
    <div>
      <%= f.text_field :title, class: 'input__field' %>
    </div>
  </div>
  <!-- Image url -->
  <div class="input">
    <div>
      <%= f.label :image_url, class: 'input__label' %>
    </div>
    <div>
      <%= f.text_field :image_url, class: 'input__field' %>
    </div>
  </div>
  <!-- Tags -->
  <div class="input">
    <div>
      <%= f.label :tag_ids, class: 'input__label' %>
    </div>
    <div>
      <%= f.collection_select( :tag_ids, Tag.order(:name), :id, :name, {}, html_options = { class: 'input__field', multiple: true})%>
    </div>
  </div>
  <!-- Spotify id -->
  <div class="input">
    <div>
      <%= f.label :spotify_code, class: 'input__label' %>
    </div>
    <div>
      <%= f.text_field :spotify_code, class: 'input__field' %>
    </div>
  </div>
  <!-- body  -->
  <div class="input">
    <div>
    <%= f.label :body, class: 'input__label' %>
    </div>
    <div class="input--textarea input--post-text">
      <%= f.text_area :body, class: 'input__field' %>
    </div>
  </div>
  
  <div class="form__text">
    <%= link_to t('edit.cancel'), account_posts_path %>
  </div>
  <!-- Submit -->
  <div class="form__text input__btn--alone">
    <div class="prompt">
    <%= f.submit class: 'btn btn--cta prompt__confirm'%>
    </div>
  </div>
<% end %>

app/views/posts/all_posts.html.erb
<div class="content-wrapper">
  <h1><%= t('header.posts') %></h1>

  <div class="tags">
    <h2><%= t('post.tags') %></h2>
    <ul class="bare-list tags__list" id="tags-list">
      <% @tags.each do |tag| %>
        <li class="btn btn--tag btn--tag--delete" id="tag-<%= tag.id %>">
          <%= link_to tag.name, name_path(tag.name) %>
          <%= link_to tag_path(tag),  role: 'button', method: :delete, remote: true do %>
              <i class="fal fa-times"></i>
              <span class="sr-only"><%= t('edit.delete') %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="tags__form form-container">
      <%= form_for @tag, html: { class: 'form'}, remote: true do |f| %>
        <%= f.label :name, class: 'input__label' %>
        <%= f.text_field :name, class: 'input__field' %>
        <%= f.submit class: 'btn btn--cta prompt__confirm'%>
      <% end %>
    </div>
  </div>
  
  <% if @posts.any? %>
    <ul class="bare-list cards post-long__list">
      <% @posts.each do |post| %>
        <li class="post-long" id="post-<%= post.id %>">
          <div class="post-long__main">
            <div class="post-long__thumb">
              <img class="avatar" src="<%= post.image_url %>" />
            </div>
            <div class="post-long__info">
              <div class="post-long__title">
                <%= link_to post_path(post), class: 'card_link' do %>
                  <%= post.title %>
                <% end %>
              </div>
              <div class="post-long__author">
                <span> <%= t('post.author') %>: <%= link_to post.user.name, username_path(post.user.username), class: 'card_link' %></span>
              </div>
              <div class="post-long__date">
                <span><%= t('post.created') %> <time datetime='<%= post.created_at %>'><%= l(post.created_at, format: :concise) %></time></span>
              </div>
              <div class="post-long__users">
                <% if  post.users.count == 1%>
                  <span><%= post.users.count %> <%= t('post.user') %></span>
                <% else %>
                  <span> <%= post.users.count %> <%= t('post.users') %></span>
                <% end %>
              </div>
            </div>
          </div>
          <div class="post-long__btn">
            <%= link_to edit_post_path(post), class: 'btn btn--icon', role: 'button' do %>
              <i class="fal fa-edit"></i> 
              <%= t('edit.modify') %>
            <% end %>
            <%= link_to post_path(post), class: 'btn btn--icon btn--warning', role: 'button', method: :delete, remote: true do %>
              <i class="fal fa-trash"></i>
              <%= t('edit.delete') %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="pagination-container">
      <%= paginate @posts %>
    </div>
  <% else %>
    <p><%= t('post.empty') %></p>
  <% end %>
</div>

app/views/posts/destroy.js.erb
Posts.removePost('<%= @post.id %>')

app/views/posts/edit.html.erb
<div class="content-wrapper">
  <!-- START Form -->
  <div class="form-container">
    <h1 class="alpha"><%= t('edit.modify') %></h1>

    <%= render 'form',  post: @post %>
  </div>
  <!-- END Form -->
</div>

app/views/posts/index.html.erb
<div class="content-wrapper">
  <% if @search_term.present? %>
    <%= render partial: 'filter', locals: { tags: @tags} %>
    <% if @posts.any? %>
    <ul class="bare-list cards">
      <% @posts.each do |post| %>
        <%= render partial: 'post_card', locals: { post: post} %>
      <% end %>
    </ul>
    <% else %>
    <p><%= t('results.search') %></p>
    <% end %>
  <% else %>
    <%= render partial: 'filter', locals: { tags: @tags} %>
    <ul class="bare-list cards">
      <% @posts.each do |post| %>
        <%= render partial: 'post_card', locals: { post: post} %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="content-wrapper">
  <!-- START Form -->
  <div class="form-container">
    <h1 class="alpha"><%= t('post.newPost') %> </h1>

    <%= render partial: 'form',  locals: { post: @post } %>
  </div>
  <!-- END Form -->
</div>

app/views/posts/show.html.erb
<% if logged_in? && can_edit_post?(@post) %>
  <div class="modify-bar">
    <div class="content-wrapper">
      <ul class="bare-list">
        <li>
          <%= link_to edit_post_path(@post), class: 'btn btn--icon', role: 'button' do %>
            <i class="fal fa-edit"></i>
            <%= t('edit.modify') %>
          <% end %>
        </li>
        <li>
          <%= link_to post_path(@post), class: 'btn btn--icon btn--warning', role: 'button', method: :delete do %>
            <i class="fal fa-trash"></i>
            <%= t('edit.delete') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>
<div class="content-wrapper">
  <article class="post">
    <div class="post__header post__section">
    <% if @post.tag_ids.present? %>
      <ul class="post__tags bare-list">
        <% @post.tags.each do |tag| %>
          <li>
            <%= link_to tag.name, name_path(tag.name), class: 'btn btn--tag' %>
          </li>
        <% end %>
      </ul>
    <% end %>
      <div class="post__title">
        <!-- Title -->
        
        <h1><%= @post.title %></h1>
      </div>
      <div class="post__header__media">
        <div class="post__meta">
          <%= image_tag(default_avatar(@post.user), alt: 'Avatar', class: 'avatar') %>
          <div class="meta-text">
            <div class="post__author">
              <!-- Author -->
              <span><%= t('post.by') %> <%= link_to @post.user.name, username_path(@post.user.username) %></span>
            </div>
            <div class="post__date">
              <!-- Date -->
              <span><time datetime="<%= @post.created_at %>"><%= l(@post.created_at, format: :long) %></time></span>
            </div>
          </div>
        </div>
        <div class="post__links">
          <%= social_share_button_tag(@post.title) %>
          <% if logged_in? %>
            <div class="post__form" id="form-post-<%= @post.id %>">
              <%= render partial: 'post_card-form', locals: { post: @post} %>
            </div>
          <% end %>
        </div>
        <!-- Add to reading list form /Remove from list-->
      </div>

      <div class="post__thumb">
        <img
          src="<%= @post.image_url %>"
          alt="Podcast" srcset="" />
      </div>
    </div>
    <div class="post__main post__section">
      <div class="post__content">
        
          <%= markdown(@post.body)%>
        
      </div>
      <% if @post.spotify_code.present? %>
        <div class="post__episode">
          <iframe src="https://open.spotify.com/embed-podcast/episode/<%= @post.spotify_code %>" width="100%"
            height="232" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
      <% end %>
    </div>
  </article>
  <%= render partial: 'comments_section',  locals: { post: @post,
                                                     comment: @comment,
                                                     comments: @comments } %>
</div>