config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|fr|es/ do
    root to: 'home#index'

    get 'about-us', to: 'home#show', as: 'about_us'

    # Account related routes
    get 'account/bookmarked', to: 'account/posts#bookmarked', as: 'bookmarked'
    get 'account/profile', to: 'account#index', as: 'profile'
    get  'account', to: 'account#edit'
    post 'account', to: 'account#update'

    namespace :account do
      resources :posts, only: [:index]
    end

    
    # Post related routes
    resources :posts do
      resources :comments, only: [:create, :destroy]
    end
    # Add comments here later
    get 'search', to: 'posts#index', as: 'search'
    get 'authors/:username', to: 'users#show', as: :username
    get 'authors/:username/posts', to: 'posts#index', as: :username_posts
    get 'all-posts', to: 'posts#all_posts', as: 'all_posts'

    # Tags related routes
    resources :tags, only: [:create, :destroy]
    get 'tags/:name', to: 'posts#index', as: :name

    # User and session related routes
    resources :sessions, only: [:new, :create, :destroy]
    resources :users do
      resources :bookmarks, only: [:create, :destroy]
    end


    # Login and Sign up routes
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    # Routes for external authentication
    get '/auth/:provider/callback', to: 'sessions#omniauth'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # Callbacks

  # Validation rules
  validates :tags, length: { maximum: 3, message: ": 3 are the maximum allowed." }
  validates :title, :body, presence: true

  # Relationships
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  has_many :comments, dependent: :destroy

  # Pagination
  paginates_per 6

  # Scopes
  scope :most_recent, -> { order(created_at: :desc).limit(6) }
  scope :title_contains, ->(term) { where('lower(title) LIKE ?', "%#{term}%") }
  scope :body_contains, ->(term) { where('lower(body) LIKE ?', "%#{term}%") }
  scope :tags_contain, ->(term) { joins(:tags).where('tags.name LIKE ?', "%#{term}%") }
  scope :search, ->(search_term) { title_contains(search_term) | tags_contain(search_term) | body_contains(search_term) }
  scope :tagged_with, ->(name) { Tag.find_by!(name: name).posts }

  # Methods

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RolesHelper

  protect_from_forgery with: :exception
  before_action :set_locale

  helper_method :logged_in?, :current_user, :admin?, :author?

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def admin?
    current_user.role == 'admin'
  end

  def author?
    current_user.role == 'author'
  end

  def ensure_authenticated
    redirect_to login_path unless logged_in?
  end

  def ensure_admin
    redirect_to root_path unless admin?
  end

  # Locale methods
  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Default avatar
  AVATAR_1 = "passifloras/curuba_1.jpeg"
  AVATAR_2 = "passifloras/granadilla.jpeg"
  AVATAR_3 = "passifloras/gulupa_2.jpeg"
  AVATAR_4 = "passifloras/maracuya_1.jpeg"
  AVATAR_5 = "passifloras/gulupa_1.jpeg"
  AVATAR_6 = "passifloras/maracuya_2.jpeg"

  def default_avatar(user)
    if user.avatar.attached?
      url_for(user.avatar)
    else
      case
        when user.name.blank?            then AVATAR_1
        when user.name[0].downcase < 'e' then AVATAR_1
        when user.name[0].downcase < 'j' then AVATAR_2
        when user.name[0].downcase < 'o' then AVATAR_3
        when user.name[0].downcase < 't' then AVATAR_4
        when user.name[0].downcase < 'w' then AVATAR_5
        else AVATAR_6
      end
    end

  end

  def pluralize_comments(comments)
    pluralize = 's' if comments.count != 1
    "#{comments.count} comment#{pluralize}"
  end

  def pluralize_users(tips)
    pluralize = 's' if tips.count != 1
    "#{tips.count} tip#{pluralize}"
  end
end

app/views/application/_featured_header.html.erb
    <!-- Start masthead -->
    <div class="masthead">
      <!-- Start Featured -->
      <div class="content-wrapper">
        <div class="featured">
          <div class="featured__header">
            <h1 class="alpha"><%= t('home.featured') %></h1>
            <span><time datetime='<%= featured.created_at %>'><%= l(featured.created_at, format: :long) %></time></span>
          </div>
          <div class="featured__thumb">
            <img
              src="<%= featured.image_url %>" srcset="" />
          </div>
          <div class="featured__main">
            <h3 class="featured__title">
              <%= link_to post_path(featured), class: 'featured_link gamma' do %>
                <%= featured.title %>
              <% end %>
            </h3>
            <% if featured.body.present? %>
              <p class="featured__text">
                <%= featured.body.truncate(160) %> <%= link_to t('home.read_more'), post_path(featured) %>
              </p>
            <% end %>
            <div class="featured__author">
            <%= link_to username_path(featured.user.username) do %>
              <%= image_tag(default_avatar(featured.user), alt: 'Avatar', class: 'avatar avatar-medium') %>
            <% end %>
              <span> <%= t('post.by') %> <%= link_to featured.user.name, username_path(featured.user.username) %></span>
            </div>
          </div>
          <div class="featured__footer">
            <% if featured.tag_ids.present? %>
              <ul class="featured__tags bare-list">
                <% featured.tags.each do |tag| %>
                  <li>
                    <%= link_to tag.name, name_path(tag.name), class: 'btn btn--tag' %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/application/_footer.html.erb
<footer class="global-footer">
    <div class="content-wrapper">
      <div class="logo logo--invert">
        <a href="/">El Rincón de la <em>Curuba</em></a>
      </div>
      <div class="nav-footer">
        <ul class="bare-list">
          <li><%= link_to t('header.us'), about_us_path %></li>
          <li><%= link_to t('header.signup'), new_user_path %></li>
        </ul>
      </div>
      <p>&copy; <a href="https://elenagoto.ch/" target="_blank">Laura Gómez</a> 2020</p>
    </div>
  </footer>

app/views/application/_header.html.erb
  <header class="header">
    <div class="header__image">
      <!-- Add here Featured image -->
      <% if @featured.present? %>
        <img src="<%= @featured.image_url %>" alt="Podcast" srcset="" />
      <% end %>
    </div>
    <!-- Start global header -->
    <div class="global-header">

      <div class="content-wrapper">
        <div class="logo">
          <%= link_to  "El Rincón de la Curuba", root_path %>
        </div>
        <div class="headers" id="show">
          <div class="hamburger" id="hamburger">
            <div></div>
          </div>
          <div class="social-media-header">
            <nav>
              <ul class="global-nav bare-list social-media-nav locales">
                <% I18n.available_locales.each do |locale| %>
                <li><%= link_to locale, url_for(locale: locale) %></li>
                <% end %>
              </ul>
            </nav>
            <nav>
              <ul class="global-nav bare-list social-media-nav">
                <li>
                  <a href="https://open.spotify.com/show/6ClS5WrBXFANCiYpdTVQNV?si=91_HREZNReaQCm9ufaZW3w" aria-label="Link to Spotify" target="_blank">
                    <i class="fab fa-spotify"></i>
                  </a>
                </li>
                <li>
                  <a href="https://www.instagram.com/olordelacuruba/" aria-label="Link to Instagram" target="_blank">
                    <i class="fab fa-instagram" ></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/Olordelacuruba" aria-label="Link to Twitter" target="_blank">
                    <i class="fab fa-twitter"></i>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <% if logged_in? %>
                <% case current_user.role
                when 'registered' %><%= render partial: 'nav_registered_user' %>
                <% when 'author' %><%= render partial: 'nav_author_user' %>
                <% when 'admin' %><%= render partial: 'nav_admin_user' %>
                <% end %>
          <% else %>
            <%= render partial: 'nav_anonymous_user' %>
          <% end %>
        </div>
      </div>
    </div>
    <% if @featured.present? %>
      <%= render partial: 'featured_header', locals: { featured: @featured } %>
    <% end %>
    <% if current_page?(search_path) || current_page?(posts_path) %>
      <%= render partial: 'search' %>
    <% end %>
  </header>

app/views/application/_nav_admin_user.html.erb
<div class="main-header">
  <nav>
    <ul class="global-nav bare-list">
      <li> 
        <%= link_to search_path do %>
          <i class="far fa-search fa-lg"></i> 
          <span class="sr-only">Buscar</span>
        <% end %>
      </li>
      <li><%= link_to t('header.users'), users_path %></li>
      <li><%= link_to t('header.posts'),  all_posts_path %></li>
      <li><%= link_to t('header.account'), profile_path %></li>
      <li><%= link_to(t('header.logout'), logout_path, method: :delete) %></li>
    </ul>
  </nav>
</div>

app/views/application/_nav_anonymous_user.html.erb
<div class="main-header">
  <nav>
    <ul class="global-nav bare-list">
      <li> 
        <%= link_to search_path do %>
          <i class="far fa-search fa-lg"></i> 
          <span class="sr-only">Buscar</span>
        <% end %>
      </li>
      <li><%= link_to t('header.us'), about_us_path %></li>
      <li><%= link_to t('header.posts'), posts_path %></li>
      <li><%= link_to t('header.login'), login_path %></li>
    </ul>
  </nav>
</div>

app/views/application/_nav_author_user.html.erb
<div class="main-header">
  <nav>
    <ul class="global-nav bare-list">
      <li> 
        <%= link_to search_path do %>
          <i class="far fa-search fa-lg"></i> 
          <span class="sr-only">Buscar</span>
        <% end %>
      </li>
      <li><%= link_to t('header.us'), about_us_path %></li>
      <li><%= link_to t('header.favorites'), bookmarked_path %></li>
      <li><%= link_to t('header.myposts'), account_posts_path %></li>
      <li><%= link_to t('header.account'), profile_path %></li>
      <li><%= link_to(t('header.logout'), logout_path, method: :delete) %></li>
    </ul>
  </nav>
</div>

app/views/application/_nav_registered_user.html.erb
<div class="main-header">
  <nav>
    <ul class="global-nav bare-list">
      <li> 
        <%= link_to search_path do %>
          <i class="far fa-search fa-lg"></i> 
          <span class="sr-only">Buscar</span>
        <% end %>
      </li>
      <li><%= link_to t('header.us'), about_us_path %></li>
      <li><%= link_to t('header.posts'), posts_path %></li>
      <li><%= link_to t('header.favorites'), bookmarked_path %></li>
      <li><%= link_to t('header.account'), profile_path %></li>
      <li><%= link_to(t('header.logout'), logout_path, method: :delete) %></li>
    </ul>
  </nav>
</div>

app/views/application/_post_card-favorite.html.erb
<li class="card" id="post-<%= post.id %>">
  <div class="card__main">
    <div class="card__thumb">
      <img src="<%= post.image_url %>" alt="Podcast" srcset="" />
    </div>
    <% if post.tag_ids.present? %>
      <ul class="card__footer bare-list">
        <% post.tags.each do |tag| %>
          <li>
            <%= link_to tag.name, name_path(tag.name), class: 'btn btn--tag' %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="card__intro">
      <h3 class="card__title gamma">
      <%= link_to post_path(post), class: 'card_link' do %>
        <%= post.title %>
      <% end %>
      </h3>
      <% if post.body.present? %>
        <h5 class="card__text">
          <%= post.body.truncate(160) %>
        </h5>
      <% end %>
    </div>
    
    <% if logged_in? %>
      <div class="card__form">
        <% if current_user.bookmarked_posts.exists?(post.id) %>
          <%= link_to user_bookmark_path(current_user, id: post.id), class: 'btn icon favorite-delete', role: 'button', method: :delete, remote: true do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="card__meta">
    <%= link_to username_path(post.user.username), class: 'card__meta__avatar' do %>
      <%= image_tag(default_avatar(post.user), alt: 'Avatar', class: 'avatar avatar-small') %>
    <% end %>
    <span><%= t('post.by') %> <%= link_to post.user.name, username_path(post.user.username) %> - <time datetime='<%= post.created_at %>'><%= l(post.created_at, format: :concise) %></time></span>
  </div>
</li>

app/views/application/_post_card-form.html.erb
<% if current_user.bookmarked_posts.exists?(post.id) %>
  <%# delete link visible %>
  <%= link_to user_bookmark_path(current_user, id: post.id), class: 'btn icon favorite-delete', role: 'button', method: :delete, remote: true do %>
    <span class="fas fa-bookmark"></span>
  <% end %>
  <%# form invisible %>
  <%= form_tag user_bookmarks_path(current_user), class: 'favorite-add invisible ', method: :post, remote: true do  %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag class: 'btn icon', type: 'submit' do %>
      <i class="fal fa-bookmark"></i>
    <% end %>
  <% end %>
<% else %>
  <%# delete link invisible %>
  <%= link_to user_bookmark_path(current_user, id: post.id), class: 'btn icon favorite-delete invisible', role: 'button', method: :delete, remote: true do %>
    <span class="fas fa-bookmark"></span>
  <% end %>
  <%# form visible %>
  <%= form_tag user_bookmarks_path(current_user), class: 'favorite-add', method: :post, remote: true do  %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag class: 'btn icon', type: 'submit' do %>
      <i class="fal fa-bookmark"></i>
    <% end %>
  <% end %>
<% end %>

app/views/application/_post_card.html.erb
<li class="card" id="card-<%= post.id %>">
  <div class="card__main">
    <div class="card__thumb">
      <img src="<%= post.image_url %>" alt="Podcast" srcset="" />
    </div>
    <% if post.tag_ids.present? %>
      <ul class="card__footer bare-list">
        <% post.tags.each do |tag| %>
          <li class="tag">
            <%= link_to tag.name, name_path(tag.name), class: 'btn btn--tag' %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="card__intro">
      <h3 class="card__title gamma">
      <%= link_to post_path(post), class: 'card_link' do %>
        <%= post.title %>
      <% end %>
      </h3>
      <% if post.body.present? %>
        <h5 class="card__text">
          <%= post.body.truncate(160) %>
        </h5>
      <% end %>
    </div>
    
    <% if logged_in? %>
      <div class="card__form" id="form-post-<%= post.id %>">
        <%= render partial: 'post_card-form', locals: { post: post} %>
      </div>
    <% end %>
  </div>
  <div class="card__meta">
    <%= link_to username_path(post.user.username), class: 'card__meta__avatar' do %>
      <%= image_tag(default_avatar(post.user), alt: 'Avatar', class: 'avatar avatar-small') %>
    <% end %>
    <span><%= t('post.by') %> <%= link_to post.user.name, username_path(post.user.username) %> - <time datetime='<%= post.created_at %>'><%= l(post.created_at, format: :concise) %></time></span>
  </div>
</li>

app/views/application/_search.html.erb
<!-- START Masthead -->
<div class="masthead">
  <div class="content-wrapper">
    <!-- START Search form -->
    <%= form_tag(search_path, class: 'search search--cta', method: 'GET') do %>
      <!-- START Label -->
      <%= label_tag('global-search', t('search'), class: 'search__label sr-only', id: 'form-search') %>
      <!-- END Label -->
      <!-- START Search row -->
      <div class="search__row">
        <% if @search_term.present? %>
          <%= text_field_tag 'q', nil, class: 'search__field', id: 'global-search', placeholder: t('search'), value: @search_term %>
        <% else %>
          <%= text_field_tag 'q', nil, class: 'search__field', id: 'global-search', placeholder: t('search') %>
        <% end %>
        
        <%= submit_tag t('search'), class: "sr-only" %>
          <%= button_tag 'Reset', type: 'reset', class: 'target icon__big', id: 'reset' do %>
        <i class="fal fa-times-circle target"></i>
        <% end %>
      </div>
      <!-- END Search row -->

    <% end %>

    <!-- END Search form -->
  </div>
</div>
<!-- END Masthead -->